spring.datasource:
  url: jdbc:h2:mem:test
  driver-class-name: org.h2.Driver

camunda.bpm.admin-user:
  id: admin
  password: admin
camunda.bpm:
  database: h2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


camunda:
  bpm:
    database:
      type: h2

